### ISSUE TITLE
Automate release action 

### ISSUE THREAD

**Issue by nachovizzo** [PRBonn/kiss-icp#110]
I managed to automate the deployment of the macOS, Windows and Linux Python packages **once** a new Release is created in GitHub. In general, I do this manually (by clicking on the web interface) , and only after I manually bump the "version number " on all possible files, which so far are:

- cpp/kiss_icp/CMakeLists.txt
- python/CMakeLists.txt
- python/kiss_icp/__init__.py
- python/setup.cfg
- ros/CMakeLists.txt
- ros/package.xml

The idea of this issue is to automate this process every time a new tag is created. Every time a new release want to be created,  we could use a script ( using the GH CLI for example) that does the following:
- [ ] The version gets automatically bumped in the files mentioned
- [ ] A new git tag is created with the number of the release
- [ ] The release notes get automatically generated from the commits since prev release
- [ ] The contributors are acknowledged
- [ ] The CI artifacts are also available (python wheels maybe)
- [ ] A new ros-distro update is launched
- [ ] (Optionally) Add extra release notes

**Comment by kumar-sanjeeev** [comment]
Hello @nachovizzo ,

If this issue is still open to work on, I am interested in contributing to this.

My first-hand approach:
I plan to create a new yml file in .github/workflows directory that will do all the tasks mentioned by you. 

I also have one question, do you want me to complete all the mentioned tasks in a single PR, or can I also complete all tasks in multiple PR?

Regards,
Sanjeev

**Comment by nachovizzo** [comment]
@kumar-sanjeeev I'm glad that you are interested in contributing!

One PR for all the tasks should be enough; more will become more complex to manage.

Be aware. That I didn't know, but Github already supports creating automatically [release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). This is something we should probably use from them to work a bit less 😉

Go for the yaml approach if you feel it is best; I'm honestly not sure which is the "best option" for doing this. Maybe checking out some online libraries could also be a good direction (for example, Open3D)

**Comment by kumar-sanjeeev** [comment]
@nachovizzo Thanks for letting me work on this. 

I will look at both options and work on the one that best suits mentioned requirements.

And I will also check some online libraries that have already implemented automatic release. I have already gone through one open-source medical image analysis software [Napari](https://github.com/napari/napari). They have used the [release.yml](https://github.com/napari/napari/blob/main/.github/workflows/make_release.yml)  file approach for automatic release.I plan to implement something in the same direction. Feel free to correct me, If I am wrong.

**Comment by nachovizzo** [comment]
Amazing,

You can also check out [This](https://cmake-python-distributions.readthedocs.io/en/latest/make_a_release.html) as an example. All those packages also have a versioneer.py module (I never checked our what they do inside though)

**Comment by kumar-sanjeeev** [comment]
Okay, I will also look into this. :+1:
