### ISSUE TITLE
What is the role of 'VERTICAL_ANGLE_OFFSET' when loading KITTI dataset?

### ISSUE THREAD

**Issue by eat-slim** [PRBonn/kiss-icp#115]
In cpp/kiss_icp/core/Preprocessing.cpp line77:
```constexpr double VERTICAL_ANGLE_OFFSET = (0.205 * M_PI) / 180.0;```
What is the purpose of this variable and what transformations it makes to the input pcd?

**Comment by nachovizzo** [comment]
The KITTI odometry dataset has a calibration problem. Therefore, the author of IMLS-SLAM came up with this small correction factor that corrects for this distortion in the data.

If you want to see the effect, just make that number a bit bigger, recompile, and then you will see the effect on the point clouds
