### ISSUE TITLE
Study the possibility to split 32/64 bits floating point operations

### ISSUE THREAD

**Issue by nachovizzo** [PRBonn/kiss-icp#117]
In the kiss-icp core library, we use `double` literally everywhere. But many datasets, including the sensor nodes, will produce point cloud data using 32 bits only.

The idea of this issue is to
- [ ] Study if converting from 32=>64 is a real issue (runtime focused)
- [ ] Analyze the possibility to have a 32-bits pipeline or,
- [ ] Analyze if we should only rely on doubles for the non-linear optimization

**Comment by NehilDanis** [comment]
Hey, can I work on this issue?

**Comment by nachovizzo** [comment]
Hi @NehilDanis , yes, that would be amazing! We are here to help.

**Comment by nachovizzo** [comment]
Move issue to backlog due inactivity
