### ISSUE TITLE
Add automatic regression tests

### ISSUE THREAD

**Issue by nachovizzo** [PRBonn/kiss-icp#119]
This is a hard one...

As mentioned in #106, we have no real automatization on checking if there is a regression on the system when changing the code. So far, when there are some big changes, like #74 , we run the evaluation notebooks in the [eval](./eval) folder and manually check (eyeball) that everything is under "control".

Of course, this is a mess and it's not scalable. The idea would be to set up an automatic benchmark tests on all the datasets we use for evaluating the setup. That's why this is not an easy or trivial task, some parts of the datasets should be selected and place somewhere that the CI can pull and run the experiments.

If anyone has a better idea on how to simplify this whole process, ideas are MORE than welcome.

**Comment by nachovizzo** [comment]
Move issue to backlog due to inactivity

**Comment by ahans** [comment]
I don't think it's a good idea to close issues that are not resolved. Somebody looking for what to work on to help out the project will never find the "backlog". You have to search for _closed_ tickets with the label `backlog`. Sounds really too hard to me. If you really mean the `help wanted`, anything with that label should remain open.
