### ISSUE TITLE
Is it possible to save the integrated point cloud 

### ISSUE THREAD

**Issue by HTLife** [PRBonn/kiss-icp#14]
Hi, there are a `results` folder containing the trajectory result.  
However, if I want to compare the point cloud quality, are there any option in python CLI to enable the .pcd file output?

**Comment by nachovizzo** [comment]
There is a way, but honestly does not make sense. KISS-ICP is an odometry pipeline, meaning that the unique output of our system are poses (4×4 matrices).

Our internal map representation is only used to obtain the incremental pose estimation and by no means should be confused with a robotics map. It's just a local representation of the environment, and it is not a global mapping solution.

If you are looking for a 3D mapping system, you can use [VDBFusion](https://github.com/PRBonn/vdbfusion) with the poses obtained from KISS-ICP.

If you still want to use the local point cloud for other reason (for example visualization) you can use the `self.local_map.point_cloud()` method from the `Odometry` class. Be aware that the API is in beta mode and not yet stable nor documented. Another example you can find by inspecting the visualizer, where use that exact method to extract the internal map representation and plot it in the visualizer **only for debugging**
