### ISSUE TITLE
Getting bad results when lidar at small angle

### ISSUE THREAD

**Issue by JereKnuutinen** [PRBonn/kiss-icp#146]
Hi,

I get some bad results when my lidar (vlp-16) is at small angle, about 15 degrees. As you can see from figure: 
![badres](https://user-images.githubusercontent.com/107494064/233120811-6abc68d2-fba8-4d92-92cd-543e3adf83a1.png)

When my lidar is not at angle, the results are good. In other words, the motion should be planar.

I also attach my ros2bag if the authors want to take a look. The bag contains multiple topics but two needed topics are synced_pc_lidar_1 and synced_pc_lidar_2. The data from synced_pc_lidar_1 is the data that performs well and the data from synced_pc_lidar_2 topic does not perform well. 

https://drive.google.com/drive/folders/1VwJ2gjFhztBUoMdh61DKC_FGEUTrwLz3?usp=sharing

In addition, I am using the following parameters:

data:
  deskew: False
  preprocess: True
  max_range: 20.0 # can be also changed in the CLI
  min_range: 1.5

mapping:
  voxel_size: 0.1 # <- optional
  max_points_per_voxel: 20

adaptive_threshold:
  initial_threshold: 2.0
  min_motion_th: 0.1

**Comment by benemer** [comment]
Hi,

Please check out the closed issues, we already investigated the challenges of sparse sensors. See [this reply](https://github.com/PRBonn/kiss-icp/issues/128#issuecomment-1505258331) for example.

I just removed the second downsampling as described by Nacho and used the following config:

```yaml
data:
  max_range: 20.0
  min_range: 1.5

mapping:
  voxel_size: 0.5
```

and obtained these results:

**synced_pc_lidar_1**
![image](https://user-images.githubusercontent.com/38326482/233404518-ab79204a-5d41-4a4e-89ec-487fb49bfb2d.png)

**synced_pc_lidar_2**
![image](https://user-images.githubusercontent.com/38326482/233404658-70f7c3ba-26cf-46fd-91fd-2cacc3f63089.png)

**Comment by JereKnuutinen** [comment]
Thank you! Another question. In the code side what can I do if I dont care performance or execution time, I am only interested in how accurate pose eatimate is. In other word, have you made some compromises regarding on accuracy so that real time performance is met.

**Comment by JereKnuutinen** [comment]
Besides downsampling is there anything that increase runtime but would also increase accuracy of pose estimates?

**Comment by benemer** [comment]
This is hard to say in general. Our goal was to design a pipeline that realizes the most important components to work on a large variety of datasets. I guess there is definitely room to increase the accuracy on certain data, but this usually requires extending the approach or tuning the method on a specific target domain.
