### ISSUE TITLE
Is Linear Velocity considered in DeSkewScan method?

### ISSUE THREAD

**Issue by BurhanMuhyiddin** [PRBonn/kiss-icp#155]
Hi all,

First of all, I am very thankful for your beautiful work. I have read your paper which was very clear and informative. Now I am trying to study the source code. However, I stuck in the **_DeSkewScan_** method, which accepts _**skewed points, relative timestamps, start and final poses**_ as inputs and returns **_deskewed pointcloud_**. In the paper, you got relative pose between starting and final poses and calculated translational and rotational velocities. Then, based on the assumption of constant velocity model you have deskewed the pointcloud. Below I attached formulas from paper for being more precise.

![img1](https://github.com/PRBonn/kiss-icp/assets/53507114/12ff22aa-0aed-4dc0-9b8f-e663f39b2e65)
![img2](https://github.com/PRBonn/kiss-icp/assets/53507114/ce77703d-b095-4a78-9e5f-97801aee8061)

However, in the source code on method **_DeSkewScan_** only rotational velocity has been taken into account. May I know why? Or am I missing the linear velocity part? Also, is **_mid_pose_timestamp_** corresponds to **_delta_t_**, namely lidar acquisition time?

![img3](https://github.com/PRBonn/kiss-icp/assets/53507114/0defb137-fd8a-4e96-8c80-b30cf84dfe07)

Thank you very much for your effort and time.

**Comment by YuePanEdward** [comment]
Here the SE3 pose is used, so I think both the translation (linear velocity) and rotation (rotational velocity) are considered.

**Comment by BurhanMuhyiddin** [comment]
@YuePanEdward Thank you for your answer.  Indeed I am still surprised that how I didn't see that in the code SE3 pose is used :)
