### ISSUE TITLE
Unfilled covariance matrix in odometry messsage

### ISSUE THREAD

**Issue by fakca** [PRBonn/kiss-icp#168]
Hi,
I am using odometry_node for ros1 to use the odometry published by kiss_icp in my localization package as a measurement. But there is no covariance published to the /odometry_node/odometry topic. I have checked the code where the message is filled up. And it seems the covariance matrix for that message is unfilled ([133-145](https://github.com/PRBonn/kiss-icp/blob/493de533a3a7fea0ff66e58f19068f0f46c1b1b7/ros/ros1/OdometryServer.cpp#LL133C1-L145C39))

I would like to ask if there is a reason for this empty covariance.
Can we add covariance to the message?

Thank you.

**Comment by nachovizzo** [comment]
Duplicated of #52
