### ISSUE TITLE
Point Cloud pre-processing required?

### ISSUE THREAD

**Issue by SvenMuc** [PRBonn/kiss-icp#170]
Hello,

I'm wondering, if I need to pre-process my point cloud in order to make kiss-icp export the 6DOF poses correctly into the kitti format.

The point cloud is provided in the sensor frame.
The sensor is mounted in a certain height (2.5 m) and with a pitch angle (~16 deg).

The matching in the Open3D visualization looks perfect.

**Top View**
<img width="946" alt="2023-05-26 11_01_55-D2209234 - TeamViewer" src="https://github.com/PRBonn/kiss-icp/assets/13385716/a2aa56b3-2122-4ec9-8e0e-dacf0e47d48e">

**Side View**
<img width="1058" alt="2023-05-26 10_58_39-D2209234 - TeamViewer" src="https://github.com/PRBonn/kiss-icp/assets/13385716/4f67dba5-94d7-4e02-9819-c42595b4bca7">

But in the exported poses I see an increasing height tz.
Everything seems to be pitched.

<img width="524" alt="2023-05-26 11_30_50-D2209234 - TeamViewer" src="https://github.com/PRBonn/kiss-icp/assets/13385716/1eabd2ef-a841-4d55-80b9-c253607e4534">

<img width="407" alt="2023-05-26 11_30_42-D2209234 - TeamViewer" src="https://github.com/PRBonn/kiss-icp/assets/13385716/10129239-0c15-43b3-867c-bb761450bdd8">

**Comment by nachovizzo** [comment]
@SvenMuc this looks interesting 🤔

Would you mind sharing the data so we can test it in house?

**Comment by benemer** [comment]
How large is the data? If possible, you could upload it to a cloud storage space (Google Drive, Dropbox) and send us the link via email. You can find our contact details [here](https://www.ipb.uni-bonn.de/people/). Thanks!

**Comment by SvenMuc** [comment]
The zip File is 25 GBs which is currently not supported by an free storage spaces.
I think I need to cut the rosbag into a smaler sequence.

**Comment by SvenMuc** [comment]
@benemer and @nachovizzo I send you a PM with the data.
