### ISSUE TITLE
Pointclouds from my simulation and pointclouds published by the "frame" topic have different orientations

### ISSUE THREAD

**Issue by sagarvl96** [PRBonn/kiss-icp#172]
I am trying to map my environment with your algorithm. I have provided the topic where the points are published by my lidar in the simulation. However, when I visualize the /frame topic on Rviz then I notice that it is in a different orientation as compared to the lidar topic of my simulation. The same is the case with the trajectory drawn. Do you maybe have any suggestions on this problem?

**Comment by nachovizzo** [comment]
Without access to the data, there is not much we can do.

If you want some help, please try to put some effort into explaining your setup, environment, etc

**Comment by lucierynd** [comment]
> I am trying to map my environment with your algorithm. I have provided the topic where the points are published by my lidar in the simulation. However, when I visualize the /frame topic on Rviz then I notice that it is in a different orientation as compared to the lidar topic of my simulation. The same is the case with the trajectory drawn. Do you maybe have any suggestions on this problem?

I am having the same issue, therefore when I visualise the odometry produced by kiss icp on rviz, the arrow are pointing in the opposite direction and the local map point cloud is appearing behind my robot even though I am using a forward facing solid state lidar. Did you find any solution ?
