### ISSUE TITLE
In which frame has the laser scan data to be

### ISSUE THREAD

**Issue by maxkremmel** [PRBonn/kiss-icp#174]
Hi all, 
The tf's of my robot look as follows:
![grafik](https://github.com/PRBonn/kiss-icp/assets/51705236/a3442a22-9d1f-445a-b842-317cc0b54fac)

As you can see, the tf of the laser scan (velodyne) is above and behind the base_link. 
As a result, kiss spits out the odometry in the velodyne frame (you can see that in the following GIF). What do I need to change or to do to get the LiDAR odometry in the base_link frame?
![Unbenanntes-Video-–-Mit-Clipchamp-erstellt](https://github.com/PRBonn/kiss-icp/assets/51705236/12819a78-5b09-4da3-9ab2-504b865ef0e7)

Do I have to convert the lidar data first into the base_link frame?

Thanks in advance.
Max

**Comment by nachovizzo** [comment]
Just tell the ros node your child frame, for example, `child_frame:=base`. Maybe related to #92

**Comment by nachovizzo** [comment]
Please check if this fix your issue https://github.com/PRBonn/kiss-icp/pull/232 


Apologize for the delay in the fix!
