### ISSUE TITLE
Any way to incorporate IMU information in KISS-ICP?

### ISSUE THREAD

**Issue by siddharth130500** [PRBonn/kiss-icp#181]
I have a Lidar point cloud data along with IMU information, although I do not have any GPS data. Is there any way we can use IMU data to improve the localization performed by KISS-ICP? I have the following information in the IMU data: angular velocity and their covariances, linear acceleration and their covariances.

**Comment by nachovizzo** [comment]
You can use it for the prediction motion module, more details in the paper. We currently don't support this in our code
