### ISSUE TITLE
5m range tiny lidar

### ISSUE THREAD

**Issue by Genozen** [PRBonn/kiss-icp#186]
Hello, I have tried Kiss-icp on Intel realsense D435i and it works fine despite the short range it provides.

I was wondering if theoretically a 5 meter max distance small ToF lidar is possible with this algorithm? Or what would be a theoretical minimum resolution on ptcloud/shape and distance?

**Comment by nachovizzo** [comment]
Hello, we would love it if you could post some data here so we can also have a look ;)

In terms of "theoretical limit", there is no such thing. Something that is worth mentioning, as we did in the paper, is that: By default, the voxel size of the internal map used to compute the odometry is inferred from the `max_range` given. In most cases, this works just fine, but there are other cases where the voxel size must be adjusted for better performance. The best way to debug this is by inspecting the visualizer we provided with the Python package. On the other hand, be aware that the `min_range` is also, by default 5m, meaning that if your maximum is that same range, there might be some problems (you probably got a warning already if using the Python package). Another thing you could try is to disable the "double downsampling" and just use one downsampling instead. You can find some hints on how to do this [here](https://github.com/PRBonn/kiss-icp/issues/128#issuecomment-1505258331)

You can checkout the [advanced config file](https://github.com/PRBonn/kiss-icp/blob/main/config/advanced.yaml) for changing all this parameters.

**Comment by Genozen** [comment]
@nachovizzo  Thanks for the swift reply!

I would love to provide the dataset!

Is there a specific data structure that I'll need for the Kiss-ICP Python edition? I have not had enough time to look through the code base and documentation, would a timestamp ptcloud (ply) be sufficient? 

When I was testing the Kiss-ICP with D435i camera, it was solely plug-and-play on ROS2 Humble, but with this new sensor, I lost the ability to collect in ROSbag format.

**Comment by nachovizzo** [comment]
For python you can also use ROS 1 bagfiles, ROS 2 bagfiles, mcap files, etc. You can also just dump the data in any format (.ply, .obj, , etc) and read it with the pipeline. just `pip install -U kiss-icp` and then run `kiss_icp_pipeline --help` ;) that should do the job
