### ISSUE TITLE
Mistake in 'kiss-icp/python/kiss_icp/datasets/boreas.py' load_poses

### ISSUE THREAD

**Issue by kurthobein** [PRBonn/kiss-icp#187]
[boreas.py](https://github.com/PRBonn/kiss-icp/blob/main/python/kiss_icp/datasets/boreas.py) line 52 and 57 use variable y for both the Y-Coordinate and the yaw which leads to wrong GT poses.

**Comment by nachovizzo** [comment]
Aha! Good catch!

Would you mind making your first open-soruce contribution to the project ;) ? Just open a Pull request with the changes. You find it, so you deserve the credits anyways.

Please let me know if you plan on doing this or not.

Thanks!

**Comment by korrupterkurde** [comment]
Will do. Thanks :D

**Comment by nachovizzo** [comment]
close in #190
