### ISSUE TITLE
Unintendet behaviour in kiss_icp/cpp/kiss_icp/core/VoxelHashMap.cpp `AddPoints` ?

### ISSUE THREAD

**Issue by kurthobein** [PRBonn/kiss-icp#191]
[VoxelHashMap](https://github.com/PRBonn/kiss-icp/blob/main/cpp/kiss_icp/core/VoxelHashMap.cpp) Line 155 will cast points in the interval (-voxel_size,voxel_size) (X,Y or Z coordinate) to 0 and thus into the same bucket, resulting in buckets of increased size around the X,Y and Z axes.
Is this intended bahviour?

EDIT: The same applies to [Preprocessing](https://github.com/PRBonn/kiss-icp/blob/main/cpp/kiss_icp/core/Preprocessing.cpp) `VoxelDownsample` Line 50
EDIT 2: Solution would be to first floor the points and then cast to int.

**Comment by tizianoGuadagnino** [comment]
Hi @kurthobein, the minimum range that one set in KISS is already above any reasonable `voxel_size` for most LiDARs. Also the points are added in global frame to the map, so the number of scans that will be integrated is relatively small. For those reasons, we didn't felt it was relevant to floor the point coordinates.
