### ISSUE TITLE
Understanding Registration

### ISSUE THREAD

**Issue by OsamaAlAhmadieh** [PRBonn/kiss-icp#211]
Hello, 

Thanks for the super structured and well written code ! 

I am trying to understand the regsitration more, specifically i am looking at the [Registration.cpp](https://github.com/PRBonn/kiss-icp/blob/main/cpp/kiss_icp/core/Registration.cpp) file. If I understood correctly, in the `AlignClouds` function, you are only doing 1 iteration of Gauss-Newton. 
My understanding of Gauss-Newton however is that we keep iterating until convergence. So we would have the icp iterations (call them outer iterations), and the individual iterations of the gauss newton (call them inner iterations) that is run within each icp loop. Is there something I am missing? Or is 1 update usually enough, since, we are still also iterating outerly in the icp loop? 

Thank you!

**Comment by nachovizzo** [comment]
@OsamaAlAhmadieh, the loop is part of the method, I'd recommend checking out the notebook done by Igor [here](https://nbviewer.org/github/niosus/notebooks/blob/master/least_squares.ipynb) to gain some more insights about the optimization.

Another way of reasoning this is, if the correspondences does not change the, the solution will not move anywhere! I hope the notebooks help understand this.
