### ISSUE TITLE
How to estimate single variable in ego pose?

### ISSUE THREAD

**Issue by poodarchu** [PRBonn/kiss-icp#212]
If part of the GT poses is already known, how to modify the code to only estimate the missing part of the ego pose.

for example, if I've already know the X-Y translation and the rotation matrix of the ego pose, can I estimate the z value in translation only?

**Comment by nachovizzo** [comment]
I'm not sure if I understand what you want to do. But the easiest thing to try is to mask out the output for the values you care

Changing the estimation to produce "less" results is quite tricky and In general does not work great. You can also use your GT as an initial guess, and this way you "avoid" estimating this. You can also check more discussions on #125
