### ISSUE TITLE
ZeroDivisionError if `avg_fps == 0` during in `pipeline.py, Line 180`

### ISSUE THREAD

**Issue by kurthobein** [PRBonn/kiss-icp#217]
Title says it all. If `avg_fps == 0`, a ZeroDivisionError is thrown because `avg_ms` can not be calculated.
Simple fix: Use the `_get_fps()`, instead of `int(np.floor(_get_fps()))` in line 180

**Comment by nachovizzo** [comment]
Closed in #218
