### ISSUE TITLE
Please make tf publishing optional

### ISSUE THREAD

**Issue by jediofgever** [PRBonn/kiss-icp#220]
Hello, 
Could you consider making tf publishing optional as in a multi-sensor fusion scenario `odom->base` link collides with other publishers.

**Comment by nachovizzo** [comment]
Pubish_odom_tf is the flag you are looking for

**Comment by jediofgever** [comment]
ah ok!, this must have been added recently

**Comment by nachovizzo** [comment]
July (#149)
