### ISSUE TITLE
How do I save the generated internal map as a pcd file?

### ISSUE THREAD

**Issue by seungyeob-seon** [PRBonn/kiss-icp#223]
I want to create a hd map and save that map in python. I confirmed that a map is created using kiss-icp api, but it is relatively sparse. I would like to create a more dense map and save it as a pcd file.

Could you explain how to save internal map in python code?
Additionally, how can I make the internal map denser?

**Comment by nachovizzo** [comment]
Dump the poses with kiss icp and then use vdbfusion. Check out github 👌

**Comment by seungyeob-seon** [comment]
@nachovizzo That issue has been resolved. thank you

**Comment by pedestrain123** [comment]
> 使用 kiss icp 转储姿势，然后使用 vdbfusion。查看 github 👌

怎么解决的？请问怎么保存点云地图
