### ISSUE TITLE
Add support to generate map into .pcd format

### ISSUE THREAD

**Issue by shahabbai** [PRBonn/kiss-icp#225]
Hello. Thanks for this amazing repository. I want to ask how can I add something like rosservice to saving .pcd files for the map? or is there any other way to do it?

**Comment by nachovizzo** [comment]
Duplicate of #14, #90, and #223

**Comment by shahabbai** [comment]
Hahaha thanks. Honestly when I create this issue, I searched about it on the closed ones and found them. Sorry for duplicate question. :(
