### ISSUE TITLE
Output Ouster timestamps on python pipeline.

### ISSUE THREAD

**Issue by pierrebenet** [PRBonn/kiss-icp#234]
Hello,

I needed to output timestamp of the trajectory of ouster SLAM on tum_poses.txt.
I had to do a few modification to do so. I think this would be useful for others.
This can be easily done by these modifications on python/kiss_icp/datasets/ouster.py :
![image](https://github.com/PRBonn/kiss-icp/assets/23551051/4be4f15d-6349-44dc-84bb-50a123222841)

**Comment by nachovizzo** [comment]
Then open a PR! That would be of great benefit to the community, and your first open-source contribution ;)
