### ISSUE TITLE
Tilted lidar

### ISSUE THREAD

**Issue by arixrobotics** [PRBonn/kiss-icp#254]
Hi, 

I'm using a tilted down lidar (VLP16) on a mobile base. How should I tell kiss-icp my lidar is tilted?

**Comment by nachovizzo** [comment]
🤔 You don't. The system is independent from where the sensor is mounted. If you want to transform the poses to another coordinate frame, then you will need the calibration. But is hard to say without the full picture

PS: If you are using VLP16 please check #240

**Comment by arixrobotics** [comment]
Kiss-ICP ftw!
Turns out I could just do with some parameter tunings, no need to make it less downsampled. 

With the default parameters, I get a trajectory with wrong elevation:
![rviz_screenshot_2023_11_09-15_03_31](https://github.com/PRBonn/kiss-icp/assets/26863279/95e853ec-de9d-4947-969d-c1f22ba367cf)

With `$ roslaunch kiss_icp odometry.launch topic:=/velodyne_points max_range:=20 voxel_size:=0.5 min_range:=0.0` it manages to register correctly, showing the lidar going through the same path to and fro correctly:
![rviz_screenshot_2023_11_09-16_16_05](https://github.com/PRBonn/kiss-icp/assets/26863279/40aeb32d-793c-4428-b528-3ba71a2b5d50)

Thanks a lot!
