### ISSUE TITLE
Not working well in some situations

### ISSUE THREAD

**Issue by SangHunHan92** [PRBonn/kiss-icp#257]
Hi, thank for the ease of use and the nice result !

However, I'm getting bad results in some situations.
I download dataset from here(https://github.com/TixiaoShan/LIO-SAM), and run kiss-icp with garden_dataset.bag and rotation_dataset.bag.

![Peek 2023-11-14 20-31](https://github.com/PRBonn/kiss-icp/assets/38457117/4e975be3-a161-43b4-ac0b-d3fcd7404076)

This looks like an incorrect pose was predicted during the registration process.

Can you tell me when these situations will appear? 
Also, can you tell me about parameter tuning or hardware settings to overcome this?

**Comment by benemer** [comment]
Hey,

I had a brief look and can confirm what you observed. My first guess is that the motion is too shaky. For example, in the `rotation_dataset.bag` the sensor starts rotating fast after the first few frames and our local map will not be a good target for registration yet. In general, our constant velocity assumption will no longer hold for abrupt changes of direction which you can observe in both datasets.

In such cases, you will probably need to use information from other sensors, like the IMU.

Best
Benedikt

**Comment by SangHunHan92** [comment]
Thank very much. I now know what I need to do to capture the dataset.
