### ISSUE TITLE
Visualization fails

### ISSUE THREAD

**Issue by ManonCortial** [PRBonn/kiss-icp#258]
`kiss_icp_pipeline orleans.pcap --meta orleans.json --visualize
Ouster pcap dataloader: using metadata json:  orleans.json
[2023-11-21 08:59:01.380] [ouster::sensor] [info] parsing legacy metadata format
Pre-reading Ouster pcap to count the scans number ...
Ouster pcap total scans number:  11948
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[Open3D WARNING] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
[Open3D WARNING] Failed to create window
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/manon/anaconda3/envs/MS3D-env-310/lib/python3.10/site-packages/kiss_ic │
│ p/tools/cmd.py:229 in kiss_icp_pipeline                                      │
│                                                                              │
│   226 │   from kiss_icp.datasets import dataset_factory                      │
│   227 │   from kiss_icp.pipeline import OdometryPipeline                     │
│   228 │                                                                      │
│ ❱ 229 │   OdometryPipeline(                                                  │
│   230 │   │   dataset=dataset_factory(                                       │
│   231 │   │   │   dataloader=dataloader,                                     │
│   232 │   │   │   data_dir=data,                                             │
│                                                                              │
│ ╭──────────────────────────── locals ─────────────────────────────╮          │
│ │           config = None                                         │          │
│ │             data = PosixPath('orleans.pcap')                    │          │
│ │       dataloader = 'ouster'                                     │          │
│ │  dataset_factory = <function dataset_factory at 0x7f536548a8c0> │          │
│ │           deskew = False                                        │          │
│ │             jump = 0                                            │          │
│ │        max_range = None                                         │          │
│ │             meta = PosixPath('orleans.json')                    │          │
│ │          n_scans = -1                                           │          │
│ │ OdometryPipeline = <class 'kiss_icp.pipeline.OdometryPipeline'> │          │
│ │         sequence = None                                         │          │
│ │            topic = None                                         │          │
│ │          version = None                                         │          │
│ │        visualize = True                                         │          │
│ ╰─────────────────────────────────────────────────────────────────╯          │
│                                                                              │
│ /home/manon/anaconda3/envs/MS3D-env-310/lib/python3.10/site-packages/kiss_ic │
│ p/pipeline.py:79 in __init__                                                 │
│                                                                              │
│    76 │   │   )                                                              │
│    77 │   │                                                                  │
│    78 │   │   # Visualizer                                                   │
│ ❱  79 │   │   self.visualizer = RegistrationVisualizer() if visualize else S │
│    80 │   │   if hasattr(self._dataset, "use_global_visualizer"):            │
│    81 │   │   │   self.visualizer.global_view = self._dataset.use_global_vis │
│    82                                                                        │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │    config = None                                                         │ │
│ │   dataset = <kiss_icp.datasets.ouster.OusterDataloader object at         │ │
│ │             0x7f536549c880>                                              │ │
│ │    deskew = False                                                        │ │
│ │      jump = 0                                                            │ │
│ │ max_range = None                                                         │ │
│ │   n_scans = -1                                                           │ │
│ │      self = <kiss_icp.pipeline.OdometryPipeline object at                │ │
│ │             0x7f536549ccd0>                                              │ │
│ │ visualize = True                                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /home/manon/anaconda3/envs/MS3D-env-310/lib/python3.10/site-packages/kiss_ic │
│ p/tools/visualizer.py:70 in __init__                                         │
│                                                                              │
│    67 │   │   # Initialize visualizer                                        │
│    68 │   │   self.vis = self.o3d.visualization.VisualizerWithKeyCallback()  │
│    69 │   │   self._register_key_callbacks()                                 │
│ ❱  70 │   │   self._initialize_visualizer()                                  │
│    71 │   │                                                                  │
│    72 │   │   # Visualization options                                        │
│    73 │   │   self.render_map = True                                         │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │ self = <kiss_icp.tools.visualizer.RegistrationVisualizer object at       │ │
│ │        0x7f53558368c0>                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /home/manon/anaconda3/envs/MS3D-env-310/lib/python3.10/site-packages/kiss_ic │
│ p/tools/visualizer.py:102 in _initialize_visualizer                          │
│                                                                              │
│    99 │   │   self.vis.add_geometry(self.source)                             │
│   100 │   │   self.vis.add_geometry(self.keypoints)                          │
│   101 │   │   self.vis.add_geometry(self.target)                             │
│ ❱ 102 │   │   self._set_black_background(self.vis)                           │
│   103 │   │   self.vis.get_render_option().point_size = 1                    │
│   104 │   │   print(                                                         │
│   105 │   │   │   f"{w_name} initialized. Press:\n"                          │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │   self = <kiss_icp.tools.visualizer.RegistrationVisualizer object at     │ │
│ │          0x7f53558368c0>                                                 │ │
│ │ w_name = 'RegistrationVisualizer'                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /home/manon/anaconda3/envs/MS3D-env-310/lib/python3.10/site-packages/kiss_ic │
│ p/tools/visualizer.py:137 in _set_black_background                           │
│                                                                              │
│   134 │   │   self._register_key_callback(["W"], self._set_white_background) │
│   135 │                                                                      │
│   136 │   def _set_black_background(self, vis):                              │
│ ❱ 137 │   │   vis.get_render_option().background_color = [0.0, 0.0, 0.0]     │
│   138 │                                                                      │
│   139 │   def _set_white_background(self, vis):                              │
│   140 │   │   vis.get_render_option().background_color = [1.0, 1.0, 1.0]     │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │ self = <kiss_icp.tools.visualizer.RegistrationVisualizer object at       │ │
│ │        0x7f53558368c0>                                                   │ │
│ │  vis = VisualizerWithKeyCallback with name RegistrationVisualizer        │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'background_color'
`

KISS-ICP Version: 0.2.10

I am inside a conda environment with cuda 11.8

**Comment by nachovizzo** [comment]
Hello @ManonCortial 

Honestly, it's a bit hard to go through the error log in the format you pasted it :) but nevertheless, it's a problem with your drivers:
```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file:
```

And moreover, it also seems to be a problem with conda, we don't support conda or any friends, kiss-icp works without the need for such fancy environments

Check out this answer https://stackoverflow.com/questions/72110384/libgl-error-mesa-loader-failed-to-open-iris
