### ISSUE TITLE
"Jerking" trajectory when using KISS-ICP

### ISSUE THREAD

**Issue by dhunnyzaheer** [PRBonn/kiss-icp#260]
Hi,

I hope you are well. First of all, thanks for the great work!

When I am trying to use KISS-ICP for my own dataset, the trajectory seems a bit "jerky". Sometimes, you can even see the path going backward and forward. I tried using different configurations but they proved to be ineffective.

The dataset was recorded using an Ouster OS2-128.

![image](https://github.com/PRBonn/kiss-icp/assets/83078916/01a3f5fe-26c4-48db-acc5-a8d05a834272)

The dataset can be found [here](https://drive.google.com/drive/folders/1LvGVt5uqq2RlE1EI6GkfGko31Edz_GJf?usp=sharing)

**Comment by nachovizzo** [comment]
Hello, kiss-icp works in an ego-centric fashion. This means we assume all the pointclouds are in the lidar-coordinate frame. Your data looks quite strange, and it's clearly in another coordinate frame, I had to zoom out a lot to see where it was:
![image](https://github.com/PRBonn/kiss-icp/assets/21349875/bbfefefb-d6fd-4a3a-a00b-ebe4982b9773)

If you are using ROS then you can specify a different target frame for the odometric frame, but that data you share won't work with kiss-icp and won't work with any other pipeline out there 

Good luck
