### ISSUE TITLE
save pose.txt from kiss_icp output in kitti dataset.

### ISSUE THREAD

**Issue by Kin-Zhang** [PRBonn/kiss-icp#267]
Hi,

Thank you for this work!

I'm wondering if there is any config we can directly save a `pose.txt` file when we run the kitti dataset like following one:

```bash
kiss_icp_pipeline --dataloader kitti --sequence 07 --visualize /home/kin/data
```

I got the score in the last, but wondering if could we also save the pose.txt from kiss_icp.

print result, want to save kiss_icp output `pose.txt`
```bash
 ───────────────────────────────────────────────── 
                           Metric   Value   Units  
 ───────────────────────────────────────────────── 
        Average Translation Error   0.327   %      
         Average Rotational Error   0.161   deg/m  
  Absoulte Trajectory Error (ATE)   0.758   m      
  Absoulte Rotational Error (ARE)   0.007   rad    
                Average Frequency    105    Hz     
                  Average Runtime     9     ms     
 ───────────────────────────────────────────────── 
```

other related issue: https://github.com/PRBonn/semantic-kitti-api/issues/140#issuecomment-1885640524 (for a downstream task to have a different odometry algorithm to check the effect.

Thanks in advance!

**Comment by nachovizzo** [comment]
all poses will be in your `./results/` directory. You have KITTI format, TUM format, and numpy format

Enjoy!

**Comment by Kin-Zhang** [comment]
So quick! Thanks @nachovizzo  ❤️
