### ISSUE TITLE
Map becomes invisible in global view

### ISSUE THREAD

**Issue by benemer** [PRBonn/kiss-icp#268]
When using the global view in the visualizer and the default black background, the local map's x and y coordinates will quickly go out of the bounds of the colormap and will be rendered just black and therefore invisible. This looks like the registration failed and lost the map, but it's just rendering:

![image](https://github.com/PRBonn/kiss-icp/assets/38326482/4a901bd6-a000-4be1-9c58-d93df47204fe)

The easiest solution would be to paint the map when using the global view.

**Comment by tizianoGuadagnino** [comment]
Solved in #269
