### ISSUE TITLE
Autocompute ICP covariance

### ISSUE THREAD

**Issue by nachovizzo** [PRBonn/kiss-icp#296]
Follow up the fixed covariance introduced in https://github.com/PRBonn/kiss-icp/pull/283 and add an option to auto-compute covariance from the ICP loop

**Comment by michael-code19** [comment]
Hi, we are interested in using your library and would like computed covariances, is this available now or is it an upcoming feature? Alternatively I might be able to work on adding it.

**Comment by tizianoGuadagnino** [comment]
Hi, I'm currently working on this feature. You can see that in the branch associated with this issue. It might get some time to get it in the state that me and the others like but it is gonna be there at some point.

**Comment by tizianoGuadagnino** [comment]
@nachovizzo @benemer shall we close this and open it again later?

**Comment by nachovizzo** [comment]
Or mark is a draft?   but yes, I won't be able to look into this, in at least 3/5 months
