### ISSUE TITLE
Issue when building file missing or has a wrong name

### ISSUE THREAD

**Issue by xaxam2001** [PRBonn/kiss-icp#298]
Hi,
when trying to build after cloning using the command `make editable`

I had this error:
```sh
 CMake Error at build/cp310-cp310-manylinux_2_35_x86_64/_deps/eigen-build/Eigen3Config.cmake:14 (include):
    include could not find requested file:

      /home/maxime/.local/lib/python3.10/site-packages/kiss_icp/python/build/cp310-cp310-manylinux_2_35_x86_64/_deps/eigen-build/Eigen3Targets.cmake
  Call Stack (most recent call first):
    /home/maxime/.local/lib/python3.10/site-packages/kiss_icp/cpp/kiss_icp/3rdparty/find_dependencies.cmake:32 (find_package)
    /home/maxime/.local/lib/python3.10/site-packages/kiss_icp/cpp/kiss_icp/3rdparty/find_dependencies.cmake:40 (find_external_dependecy)
    /home/maxime/.local/lib/python3.10/site-packages/kiss_icp/cpp/kiss_icp/CMakeLists.txt:48 (include)
```

I resolved it by changing the name of `Eigen3Targets.cmake` to `Eigen3ConfigVersion.cmake` inside the `Eigen3Config.cmake` file.

(those 3 files are contained inside: `kiss_icp/python/build/cp310-cp310-manylinux_2_35_x86_64/_deps/eigen-build/` )

I'm not sure if it's the right way to resolve the issue but it's working fine now.

**Comment by nachovizzo** [comment]
Hello! Thanks for reporting this!

The `editable` target is only used, and supported by the mantainers of the project. We can't provide support to all the infinite amount of configurations out there, therefore, the default `make` target is the official one if you want to build from the source
