### ISSUE TITLE
Kiss-icp timestamp management with rosbags

### ISSUE THREAD

**Issue by ClementLeBihan** [PRBonn/kiss-icp#319]
Hi,
I found some weird timestamp management in kiss-icp and would like to discuss with you about this : 

- First, you get the msg stamp using `connection, timestamp, rawdata = next(self.msgs)` in rosbag.py, but the timestamp corresponds to bag stamp instead of msg header stamp. If you have delay between lidar driver publish msg and rosbag writing it in the bag, you'll get a difference between msg header stamp and the msg written stamp.
- Then, in point_cloud2.py, you normalized lidar point stamp between 0 and 1 to deskew using two poses. Unfortunately, if you have a 360° degree that scan only a part of the fov (let's say 180°), you'll do a mistake in deskew. To make it cleaner, you should keep the real timestamp and compare it to the delta stamp in deskew.
- Third, in deskew.cpp, you use (timestamp - 0.5) * deltaPose. In this case, you descew around mid point (0.5) and so finale pose you'll find using this pointcloud will correspond to the pose of the sensor at the middle of the scan (and not the pointcloud original timestamp). Unfortunately, most of lidar drivers use the PointCloud2 header stamp as either the stamp of the begining of the scan, either the end of the scan, but never the middle of the scan.

What do you think about these issues ? Have you ever tryied to rewrite a rosbag with tfs from the result file and accumulate it in rviz to see the problem ?

**Comment by nachovizzo** [comment]
So, as a general view (at least my view) but probably the guys will also agree:

The python rosbag dataloader should only used for fast prototyping, and to have a quick look if the system is "promising enough or not".  But when dealing with real robots, or live data, the ROS wrapper should be used in combination to whatever system you are using.

We don't go too fancy with the python rosbags as it's only an entry point to the system. Something we found unexisting in the community (you typically need to compile outaded code, with unknown dependencies, for ubuntu 18.04, fix the build, and after 3 days run it to realize it was not working with your data)

That said, now the reply:

> First, you get the msg stamp using connection, timestamp, rawdata = next(self.msgs) in rosbag.py, but the timestamp corresponds to bag stamp instead of msg header stamp. If you have delay between lidar driver publish msg and rosbag writing it in the bag, you'll get a difference between msg header stamp and the msg written stamp.

I consider this a bug, so feel free to open a PR. The header should be the `msg.header.stamp`, as we do it in the ROS wrapper. In any case this timestamp is NOT used for pointcloud deskewing, it's just to provide support for writing poses in TUM format

> Then, in point_cloud2.py, you normalized lidar point stamp between 0 and 1 to deskew using two poses. Unfortunately, if you have a 360° degree that scan only a part of the fov (let's say 180°), you'll do a mistake in deskew. To make it cleaner, you should keep the real timestamp and compare it to the delta stamp in deskew.
I didn't get this point :)

> Third, in deskew.cpp, you use (timestamp - 0.5) * deltaPose. In this case, you descew around mid point (0.5) and so finale pose you'll find using this pointcloud will correspond to the pose of the sensor at the middle of the scan (and not the pointcloud original timestamp). Unfortunately, most of lidar drivers use the PointCloud2 header stamp as either the stamp of the begining of the scan, either the end of the scan, but never the middle of the scan.
Yup, this will be a problem. As a matter of fact I'm using the system in a ROS application and having the first point for stamping. It might be harder to "generalize" but happy to take a look into changes, the hacky parameter should be exposed through the API at some point anyways

Thanks for all the comments!
