### ISSUE TITLE
How to recur the poses of kitti dataset?

### ISSUE THREAD

**Issue by zcc00210** [PRBonn/kiss-icp#333]
Hello,

Thank you for sharing your work!

When I tried to recur poses.txt using the kitti 05 dataset, I used the command `kiss_icp_pipeline --visualize /home/jy/201/velodyne`, and in the /home/jy/201/velodyne directory I only used the .bin format of the kitti 05 dataset. 
![image](https://github.com/PRBonn/kiss-icp/assets/111226725/5698b1f0-92f8-4d4b-8c0b-b0619f0d5fd3)
But the resulting velodyne_poses_kitti.txt is nothing like the poses.txt in the original dataset. Although I use `evo_traj kitti results/2024-04-22_11-45-32/velodyne_poses_kitti.txt -p --plot_mod=xy` to see that the corresponding trajectories for the poses generated using kiss-icp are correct, why do the 12 numbers in each row not being correct? How can I get the same pose as in the kitti dataset?

Thanks in advance!

**Comment by nachovizzo** [comment]
First, use the kitti dataloader , second use the kitti dataset. You are using semantic kitti, those poses are from SUMA. If you want to see how the trajectory looks like for kiss icp check the eval directory from this repo
