### ISSUE TITLE
problem with biuld for ROS2

### ISSUE THREAD

**Issue by Sefilevy** [PRBonn/kiss-icp#336]
we try to build it on ROS2 by running the code: 
"git clone https://github.com/PRBonn/kiss-icp
colcon build
source ./install/setup.bash"
and we got the following error:
" colcon build
[0.892s] ERROR:colcon:colcon build: Duplicate package names not supported:
- kiss_icp:
  - kiss-icp/ros
  - src/kiss-icp/ros"

if anyone can help us- much appreciated

**Comment by nachovizzo** [comment]
You literally have 2 spaces in your workspace as the error message is telling you. You might have cloned multiple times in different directores.
