### ISSUE TITLE
Inconsistent unit (rad vs deg) in c++ and python

### ISSUE THREAD

**Issue by wing-kit** [PRBonn/kiss-icp#339]
https://github.com/PRBonn/kiss-icp/blob/main/cpp/kiss_icp/metrics/Metrics.cpp#L152
In the implementation part it is in rad/m.

https://github.com/PRBonn/kiss-icp/blob/main/python/kiss_icp/metrics.py#L30

In the rendering it says it is in deg/m.
https://github.com/PRBonn/kiss-icp/blob/main/python/kiss_icp/pipeline.py#L175

**Comment by benemer** [comment]
See https://github.com/PRBonn/kiss-icp/pull/340
