### ISSUE TITLE
Difference between paper with implementation?

### ISSUE THREAD

**Issue by mertyavuz41** [PRBonn/kiss-icp#36]
Hi,

First of all, I would like to thanks to great studies. When I examine the code I observed that difference between mentioned paper deskewing formula and implemented deskewing method. 

Formula has exp process but I could not see exp process on the code. 
Paper:
![image](https://user-images.githubusercontent.com/73120336/212544812-70c45e19-3c26-4f9a-bc7b-9fe14f255b51.png)

Code:
https://github.com/PRBonn/kiss-icp/blob/a31f5396c6153f12e9011c9ae6d061597d2f45b3/src/cpp/kiss_icp/Deskew.cpp#L58-L63

Am i missing something?

**Comment by nachovizzo** [comment]
If you read 1 line below that formula, you will find the answer to your question: 
![image](https://user-images.githubusercontent.com/21349875/212559736-eb790df5-5dcc-4b45-b0cb-b3a5ebf98c87.png)

It's not an "exponential" function, but an exponential map. I'd recommend checking out some lie algebra theory ;)

**Comment by mertyavuz41** [comment]
Thanks for your informative feedback 🙏
