### ISSUE TITLE
Geman-McClure Kernel weight function

### ISSUE THREAD

**Issue by Wayne-DWA** [PRBonn/kiss-icp#366]
Hi, I'm just wondering if the Geman-McClure kernel formula in the code is wrong: 
https://github.com/PRBonn/kiss-icp/blob/5d420877a6e5f984ea86957da9e670ff6aed45e4/cpp/kiss_icp/core/Registration.cpp#L141
since the loss function is defined in paper eq. 13:

![image](https://github.com/PRBonn/kiss-icp/assets/90710539/d2c7c3de-8895-43e8-b97d-3f54f0eea02b)

The influence function ψ(x) is the derivative of the loss function with respect to the residual and the weight function should be  the ratio of the influence function to the residual. In this way: 

```
    auto GM_weight = [&](const double &residual2) {
        return kernel_scale / square(kernel_scale + residual2);
    };
```

**Comment by nachovizzo** [comment]
Isn't this a duplicated of https://github.com/PRBonn/kiss-icp/issues/35?
