### ISSUE TITLE
Is there any parameter with which i can reduce the output frequency of the odometry ?

### ISSUE THREAD

**Issue by chrissunny94** [PRBonn/kiss-icp#367]
For some experiment , i want to kiss-icp to publish odometry at 3hz even though my lidar is publishing at 10hz . Kindly let me know if its possible from this code base itself .

**Comment by nachovizzo** [comment]
can you provide more details? are you using the python package, ROS 1, ROS 2, what is the thing you want to do?

**Comment by chrissunny94** [comment]
Sorry ,  i was down with a fever(Dengue season in Banglore 😞) , thus could not respond to this . 

I managed to get what i was looking for by simple ignoring some frames in my message filter . 

Thank you  and kind regards for the prompt reply though .
