### ISSUE TITLE
How to evaluate any rosbag files? (To get APE,RPE values)

### ISSUE THREAD

**Issue by AyshaMK** [PRBonn/kiss-icp#38]
Hi, 
I want to evaluate rosbag files. Now the output poses are obtained in kitti format. I have converted the groundtruth(which is in tum format) into kitti format. But while running evo_ape kitti gt.txt out.txt -va --plot --plot_mode xy --save_results results/ape.zip , got error as : [ERROR] data matrices must have the same shape (since the no of poses are different) and could not able to evaluate. Can you please suggest some method to evaluate any rosbag files?

**Comment by nachovizzo** [comment]
Hello,

that's actually hard to "generalize". Depending on how the data inside the rosbag was recorded, defining the ground truth for evaluating the system can be arbitrary complex. I'd recommend, as you did, obtaining the pose information from KISS-ICP and running offline evaluation scripts.

About the results:
Yes, the results are in KITTI format, but now we also save the poses in numpy format. If the evaluation script is not working, there is not much I can do from my side.

Could you send me a link to the data, so I can try it myself and see if I can run an evaluation? Thanks!

PS: You can also check the [Newer College Evaluation](https://github.com/PRBonn/kiss-icp/blob/main/eval/newer_college.ipynb) That's a rosbag dataset where we also run the evaluation (without using the evo pacakge)

**Comment by AyshaMK** [comment]
Hi ,

I have tested with HILTI- LAB dataset(8GB) -
https://hilti-challenge.com/dataset-2021.html
Kindly help me to evaluate the same.

Thank you in advance

Regards
Aysha
