### ISSUE TITLE
Question, Using Own data with Python interface

### ISSUE THREAD

**Issue by jediofgever** [PRBonn/kiss-icp#380]
Hi,
I want to try kiss-icp on my data. 
The data isn't in a standard format and is stored in a hdf5, I have the following fields for point. 

`x, y, z, intensity, timestamp`

I think kiss-icp does motion compensation/untwisting of the cloud with perpoint timestamps right? 
I am trying to figure out how to format my cloud data so that it is compatible with what kiss-ICP expects. Could you provide some help clarifying? 
Each cloud frame has its own timestamp as well, So I guess all points are transformed into cloud frame's time by accounting for ego-motion.

**Comment by benemer** [comment]
The best approach is to write your own data loader instead of changing the format of your data. Just check out the existing ones and follow their structure. To use deskewing, you need to provide per-point timestamps, that's correct!
