### ISSUE TITLE
Minimum distance of point clouds in KISS-ICP

### ISSUE THREAD

**Issue by Hajun0219** [PRBonn/kiss-icp#396]
I would like to exclude certain angles or close point clouds from KISS-ICP.

Is it possible to adjust the minimum distance or angle of point clouds in KISS-ICP?

**Comment by benemer** [comment]
You can adjust the minimum range at which our preprocessing will clip the point clouds. Just create a `config.yaml` with the following

```yaml
data:
  min_range: 0.0
```

and then pass it via the `--config` flag.

So far, it is not possible to mask out certain angles. What is the idea behind that? Anyway, you can also modify the preprocessing to exclude these angles.
