### ISSUE TITLE
Test on new datasets

### ISSUE THREAD

**Issue by rasrab1992** [PRBonn/kiss-icp#402]
Hello,
Thank you for sharing your code, it's great work.

I want to test your code on my datasets. Maximum range of my point clouds is around 1.2m and FoV of my sensor is about 70 degree. I want to use your code for 3D reconstruction of objects. What parts of your data should be changed?

**Comment by tizianoGuadagnino** [comment]
run ```kiss_icp_pipeline --help``` has reported in the README. 1.2m max range seems a bit less, you might need to touch min and max range in the configuration.
