### ISSUE TITLE
SyntaxWarning on regex

### ISSUE THREAD

**Issue by quillaja** [PRBonn/kiss-icp#405]
Just installed per instructions and got this:
```
kiss_icp\.venv\Lib\site-packages\kiss_icp\datasets\ncd.py:75: SyntaxWarning: invalid escape sequence '\d'
  regex = re.compile("^cloud_(\d*_\d*)")
```
Maybe change the regex to a raw string? `r"^cloud_(\d*_\d*)"`

**Comment by tizianoGuadagnino** [comment]
You can definetely open a pull request with that, if it works on the NCD dataset we can probably merge it right away ;)

**Comment by tizianoGuadagnino** [comment]
Close due to inactivity.
