### ISSUE TITLE
Installation fails after upgrading MacOS to Sequoia

### ISSUE THREAD

**Issue by angusleigh** [PRBonn/kiss-icp#409]
I'm not sure if it's a problem others experienced, but I thought I'd leave this here in case it's helpful. To install my on MacOS machine after upgrading to Sequoia, I had to remove and re-install xcode:

> sudo rm -rf /Library/Developer/CommandLineTools/
> xcode-select --install

I'm not sure if this report belongs here, so feel free to delete. I was thinking maybe it should just be closed though, so others can find it via search.

**Comment by tizianoGuadagnino** [comment]
Make sense; @angusleigh thank you for your reporting. I will close it, but at least it became a know thing 😄
