### ISSUE TITLE
online SLAM

### ISSUE THREAD

**Issue by lsorgi** [PRBonn/kiss-icp#43]
Hello, 

is there a way to use the library for online data processing? (see pseudocode below)
```

while True:
    pts_3d = acquire_data_from_depth_sensor()
    pose = kiss_icp(pts_3d)
```

**Comment by nachovizzo** [comment]
That wouldn't be a SLAM application, but leaving that detail aside 😉 we are currently working on a ROS wrapper that can be used for this same application.

I'll try to notify you when it's ready but you can enable notification in this repo (press watch) in case I forget to do so!

**Comment by lsorgi** [comment]
oki! 
sure, I didn't include the 'mapping' part of SLAM because I am mostly interested on camera tracking. 
thanks for the hint, I'll stay connected to see the evolution of the repo.

**Comment by nachovizzo** [comment]
> That wouldn't be a SLAM application, but leaving that detail aside 😉 we are currently working on a ROS wrapper that can be used for this same application.
> 
> I'll try to notify you when it's ready but you can enable notification in this repo (press watch) in case I forget to do so!
@lsorgi:
ROS wrapper is already available on the main branch 😉
