### ISSUE TITLE
Add Covariance

### ISSUE THREAD

**Issue by D3RUM** [PRBonn/kiss-icp#52]
I have the ros node running and it has been very easy to get up and running when compared to other options.  However, before I can integrate this into a larger system, I need covariances for the estimated odometry. Have you thought about how to compute uncertainties for the results of KISS-ICP?

Great work!! I'm excited to try this out on more datasets!

**Comment by tizianoGuadagnino** [comment]
Hi @D3RUM, we do not currently support covariance estimation for the on-going odometry. We make this choice as such an addition would complicated the implementation by a substantial margin. In fact, we should either rely on a factor graph or use covariance propagation. If you are interested in this topic, I can redirect you to some literature like https://arxiv.org/pdf/1909.05722.pdf or http://ais.informatik.uni-freiburg.de/publications/papers/tipaldiIROS07.pdf. 

In case you would like to implement the covariance estimation for KISS-ICP, we would be more than happy to welcome your contribution to the source code.

Ciao
