### ISSUE TITLE
Voxel size can not be configured using the ROS launchfile

### ISSUE THREAD

**Issue by cmuehlbacher** [PRBonn/kiss-icp#54]
The configuration value voxel_size can not be changed using a parameter in ROS. This might be of interest for indoor cases.
The fix would to expose this configuration value as it is done for the min_range, ...

**Comment by nachovizzo** [comment]
@cmuehlbacher I merged a change that enables this. As we do in the python pipeline, the voxel_size is automatically determined from the maximum range, if you are working with indoor data, then it's a good idea to reduce the max range to 10 meters or so. You can also specify the voxel_size manually if you don't want the “automatic computation”

Please let us know if this worked out ;)
