### ISSUE TITLE
Initial guess and configuration

### ISSUE THREAD

**Issue by mzdaneshmand** [PRBonn/kiss-icp#59]
I want to supply an initial guess for each point cloud. Moreover, I would like to be able to modify the configurations of the ICP runs. What exactly should a configuration file look like?

**Comment by nachovizzo** [comment]
@mzdaneshmand sorry but I don't quite get what are your needs, could you please elaborate more? What is the meaning for you of "initial guess", "configurations", etc.

Thanks!
