### ISSUE TITLE
Robesense Lidars

### ISSUE THREAD

**Issue by lucabonamini** [PRBonn/kiss-icp#60]
First of all, fantastic work! Really appreciate the defense of ICP algorithm 😄 

Had you have the chance to do some tests with a Robosense Lidar? I'd be very interested in the performance with those type of Lidars.

**Comment by nachovizzo** [comment]
Thanks!

Not so far (as far as I remember). As long as you get some 3D points, it should be possible to at least give it a try!. Do you have some dataset? We could give it a try if you could share some data with us.
