### ISSUE TITLE
deskew timestamps issue

### ISSUE THREAD

**Issue by RoniEmad** [PRBonn/kiss-icp#94]
Hello,

Thank you for your amazing work!

I was testing kiss_icp using some rosbags, but I can't get the deskew to work properly.

I guess it's timestamps problem as they are between -0.099 and 0.00064.

I've read that the timestamps are assumed to be a vector in the range of 0 and 1.0 and if not, stuff is going to be weird.

So i tried normalizing by dividing **_timestamp/max_timestamps_**
and **_(timestamp-min_timestamps)/(max_timestamps-min_timestamps)_** 
but it doesn't seem to improve the results.

I would appreciate if you can help me with this issue.

These are the [rosbags](https://drive.google.com/drive/folders/1sQ03Pa354yppHG4g7zX_YtZVq-HrxYXN?usp=sharing) i tried.

Thanks in advance!

This is a picture of the output showing the skewing:

![Screenshot from 2023-03-12 02-13-00](https://user-images.githubusercontent.com/90726457/224517229-da310493-8e9a-44ed-8d84-1c2bbf85e914.png)

**Comment by tizianoGuadagnino** [comment]
Hi, I think you can refer to Issue #95 . This should be the same 16 beam LiDAR that you are using.
