### ISSUE TITLE
Is kiss-icp assuming anything about frame rate

### ISSUE THREAD

**Issue by JereKnuutinen** [PRBonn/kiss-icp#98]
Hi,

I am just wondering if kiss-icp assumes anything regarding on frame rate (hz). The paper only states: "This follows from the fact that
robotic LiDAR sensors commonly record and stream point clouds at 10 Hz to 20 Hz, i.e., every 0.05 s to 0.1 s."

**Comment by nachovizzo** [comment]
We make absolutist no assumptions. Is the streaming rate from a sensor
